databases:
  - name: syashinn5_DB
    databaseName: syashinn5_db_8cpd
    user: syashinn5
    region: singapore

services:
  - type: web
    name: syashinn5
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: syashinn5_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

